# Generated by Django 6.0.3 on 2026-03-24 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(max_length=20, unique=True, verbose_name='类型编码')),
                ('type_name', models.CharField(max_length=100, verbose_name='类型名称')),
                ('category', models.CharField(choices=[('主机', '主机'), ('显示器', '显示器'), ('笔记本', '笔记本'), ('其他', '其他')], max_length=20, verbose_name='设备类别')),
                ('brand', models.CharField(blank=True, max_length=50, verbose_name='品牌')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='型号')),
                ('specs', models.TextField(blank=True, verbose_name='配置参数')),
                ('warranty_months', models.IntegerField(default=36, verbose_name='保修期(月)')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '计算机类型',
                'verbose_name_plural': '计算机类型管理',
                'ordering': ['type_code'],
            },
        ),
        migrations.CreateModel(
            name='OfficeSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='物品编码')),
                ('name', models.CharField(max_length=100, verbose_name='物品名称')),
                ('category', models.CharField(max_length=50, verbose_name='物品类别')),
                ('specification', models.CharField(blank=True, max_length=100, verbose_name='规格型号')),
                ('unit', models.CharField(default='个', max_length=20, verbose_name='计量单位')),
                ('quantity', models.IntegerField(default=0, verbose_name='库存数量')),
                ('safety_stock', models.IntegerField(default=10, verbose_name='安全库存')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='存放位置')),
                ('supplier', models.CharField(blank=True, max_length=100, verbose_name='供应商')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价')),
                ('status', models.CharField(choices=[('正常', '正常'), ('低库存', '低库存'), ('停用', '停用')], default='正常', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '办公用品',
                'verbose_name_plural': '办公用品库存',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ITDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_no', models.CharField(max_length=50, unique=True, verbose_name='设备编号')),
                ('asset_no', models.CharField(blank=True, max_length=50, verbose_name='资产编号')),
                ('serial_no', models.CharField(blank=True, max_length=100, verbose_name='序列号')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='采购日期')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='采购价格')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='存放位置')),
                ('user', models.CharField(blank=True, max_length=100, verbose_name='使用人')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='使用部门')),
                ('status', models.CharField(choices=[('库存', '库存'), ('使用中', '使用中'), ('维修中', '维修中'), ('报废', '报废')], default='库存', max_length=20, verbose_name='使用状态')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.computertype', verbose_name='设备类型')),
            ],
            options={
                'verbose_name': 'IT设备',
                'verbose_name_plural': 'IT设备管理',
                'ordering': ['device_no'],
            },
        ),
        migrations.CreateModel(
            name='ReturnApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_no', models.CharField(max_length=50, unique=True, verbose_name='归还单号')),
                ('quantity', models.IntegerField(verbose_name='归还数量')),
                ('returner', models.CharField(max_length=100, verbose_name='归还人')),
                ('department', models.CharField(max_length=100, verbose_name='部门')),
                ('return_date', models.DateField(verbose_name='归还日期')),
                ('reason', models.TextField(blank=True, verbose_name='归还原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作员')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.officesupply', verbose_name='物品')),
            ],
            options={
                'verbose_name': '归还申请',
                'verbose_name_plural': '归还申请管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockInApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_no', models.CharField(max_length=50, unique=True, verbose_name='申请单号')),
                ('quantity', models.IntegerField(verbose_name='申请数量')),
                ('department', models.CharField(max_length=100, verbose_name='申请部门')),
                ('reason', models.TextField(blank=True, verbose_name='申请原因')),
                ('status', models.CharField(choices=[('待审批', '待审批'), ('已批准', '已批准'), ('已拒绝', '已拒绝')], default='待审批', max_length=20, verbose_name='审批状态')),
                ('approval_time', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('approval_comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockin_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stockin_approvals', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.officesupply', verbose_name='物品')),
            ],
            options={
                'verbose_name': '入库申请',
                'verbose_name_plural': '入库申请管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockOutRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_no', models.CharField(max_length=50, unique=True, verbose_name='出库单号')),
                ('quantity', models.IntegerField(verbose_name='出库数量')),
                ('recipient', models.CharField(max_length=100, verbose_name='领用人')),
                ('department', models.CharField(max_length=100, verbose_name='领用部门')),
                ('purpose', models.TextField(blank=True, verbose_name='用途说明')),
                ('out_type', models.CharField(choices=[('领用', '领用'), ('归还', '归还'), ('报废', '报废'), ('调拨', '调拨')], default='领用', max_length=20, verbose_name='出库类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='出库时间')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作员')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.officesupply', verbose_name='物品')),
            ],
            options={
                'verbose_name': '出库记录',
                'verbose_name_plural': '出库记录管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
