# Generated by Django 6.0.3 on 2026-05-19 02:38

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockinapplication',
            name='counterpart_doc_no',
        ),
        migrations.RemoveField(
            model_name='stockinapplication',
            name='invoice_no',
        ),
        migrations.AlterField(
            model_name='profile',
            name='applied_role',
            field=models.CharField(choices=inventory.models.get_role_choices, default='staff', max_length=20, verbose_name='申请角色'),
        ),
    ]
