# Generated by Django 6.0.3 on 2026-03-24 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='类别编码')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='类别名称')),
                ('description', models.TextField(blank=True, verbose_name='类别说明')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '办公用品类别',
                'verbose_name_plural': '办公用品类别管理',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.AlterField(
            model_name='officesupply',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplycategory', verbose_name='物品类别'),
        ),
    ]
