# Generated by Django 6.0.3 on 2026-05-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_stockinapplication_counterpart_doc_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinapplication',
            name='doc_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='发票编号或对方单据编号'),
        ),
    ]
