# Generated by Django 6.0.3 on 2026-05-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockinapplication_doc_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockinapplication',
            name='doc_reference',
        ),
        migrations.AddField(
            model_name='stockinitem',
            name='doc_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='单据编号'),
        ),
        migrations.AddField(
            model_name='stockinitem',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('invoice', '发票编号'), ('counterpart', '对方单据编号')], max_length=20, verbose_name='单据类型'),
        ),
    ]
