# Generated by Django 6.0.3 on 2026-05-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_stockinapplication_doc_reference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockinitem',
            name='doc_type',
        ),
        migrations.AlterField(
            model_name='stockinitem',
            name='doc_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='发票或对方单据编号'),
        ),
    ]
