# Generated by Django 6.0.3 on 2026-04-25 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itdevice',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.department', verbose_name='使用部门'),
        ),
        migrations.AlterField(
            model_name='returnapplication',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.department', verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='stockinapplication',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.department', verbose_name='申请部门'),
        ),
        migrations.AlterField(
            model_name='stockoutrecord',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.department', verbose_name='领用部门'),
        ),
    ]
