# Generated by Django 6.0.3 on 2026-05-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_stockinitem_doc_type_alter_stockinitem_doc_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockoutitem',
            name='remark',
            field=models.CharField(blank=True, max_length=200, verbose_name='备注'),
        ),
    ]
