# Generated by Django 4.2.30 on 2026-04-25 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0006_alter_itdevice_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='出库数量')),
            ],
            options={
                'verbose_name': '出库明细',
                'verbose_name_plural': '出库明细',
            },
        ),
        migrations.CreateModel(
            name='StockOutOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_no', models.CharField(max_length=50, unique=True, verbose_name='出库单号')),
                ('recipient', models.CharField(max_length=100, verbose_name='领用人')),
                ('purpose', models.TextField(blank=True, verbose_name='用途说明')),
                ('out_type', models.CharField(choices=[('领用', '领用'), ('归还', '归还'), ('报废', '报废'), ('调拨', '调拨')], default='领用', max_length=20, verbose_name='出库类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='出库时间')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.department', verbose_name='领用部门')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作员')),
            ],
            options={
                'verbose_name': '出库单',
                'verbose_name_plural': '出库单管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='StockOutRecord',
        ),
        migrations.AddField(
            model_name='stockoutitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockoutorder', verbose_name='出库单'),
        ),
        migrations.AddField(
            model_name='stockoutitem',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.officesupply', verbose_name='物品'),
        ),
    ]
