# Generated by Django 6.0.3 on 2026-07-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_stockoutitem_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itdevice',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='itdevice',
            name='department',
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: apps.get_model(
                'inventory', 'RolePermission'
            ).objects.filter(module='it_device').delete(),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('basic_data', '基础数据管理'), ('supply', '库存管理'), ('stockin', '入库单管理'), ('stockout', '出库单管理'), ('approval', '审批管理'), ('return', '归还管理'), ('statistics', '统计报表'), ('user_management', '用户管理')], max_length=30, verbose_name='功能模块'),
        ),
        migrations.DeleteModel(
            name='ComputerType',
        ),
        migrations.DeleteModel(
            name='ITDevice',
        ),
    ]
