# Generated by Django 6.0.3 on 2026-07-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_it_device_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='applied_role',
            field=models.CharField(choices=[('admin', '管理员'), ('warehouse', '仓管员'), ('dept_head', '部门长'), ('staff', '普通用户')], default='staff', max_length=20, verbose_name='申请角色'),
        ),
    ]
