# Generated by Django 5.2.13 on 2026-04-25 08:18

import django.db.models.deletion
from django.db import migrations, models


def migrate_stockin_data(apps, schema_editor):
    """将旧入库申请的 supply/quantity 迁移到新的 StockInItem 明细表"""
    StockInApplication = apps.get_model('inventory', 'StockInApplication')
    StockInItem = apps.get_model('inventory', 'StockInItem')
    for app in StockInApplication.objects.all():
        if app._legacy_supply_id and app._legacy_quantity:
            StockInItem.objects.create(
                application=app,
                supply_id=app._legacy_supply_id,
                quantity=app._legacy_quantity,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_stockout_multiline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockinapplication',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='stockinapplication',
            name='supply',
        ),
        migrations.AddField(
            model_name='stockinapplication',
            name='_legacy_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='申请数量（旧）'),
        ),
        migrations.AddField(
            model_name='stockinapplication',
            name='_legacy_supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_stockin_applications', to='inventory.officesupply', verbose_name='物品（旧）'),
        ),
        migrations.CreateModel(
            name='StockInItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='申请数量')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockinapplication', verbose_name='入库申请')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.officesupply', verbose_name='物品')),
            ],
            options={
                'verbose_name': '入库明细',
                'verbose_name_plural': '入库明细',
            },
        ),
        # 数据迁移：将旧 StockInApplication 的 supply/quantity 迁移到 StockInItem
        migrations.RunPython(migrate_stockin_data, reverse_code=migrations.RunPython.noop),
    ]
