# Generated by Django 5.2.13 on 2026-04-26 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_stockinapplication_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officesupply',
            name='category',
        ),
        migrations.RemoveField(
            model_name='stockinapplication',
            name='_legacy_quantity',
        ),
        migrations.RemoveField(
            model_name='stockinapplication',
            name='_legacy_supply',
        ),
    ]
