# Generated by Django 5.2.13 on 2026-04-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_officesupply_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价'),
        ),
    ]
