# Generated by Django 6.0.3 on 2026-05-11 09:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_add_stockin_item_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinapplication',
            name='counterpart_doc_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='对方单据编号'),
        ),
        migrations.AddField(
            model_name='stockinapplication',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='发票编号'),
        ),
        migrations.AddField(
            model_name='stockinapplication',
            name='stockin_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='入库日期'),
        ),
    ]
