# Generated by Django 6.0.3 on 2026-05-12 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_stockinapplication_counterpart_doc_no_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockoutorder',
            name='approval_comment',
            field=models.TextField(blank=True, verbose_name='审批意见'),
        ),
        migrations.AddField(
            model_name='stockoutorder',
            name='approval_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审批时间'),
        ),
        migrations.AddField(
            model_name='stockoutorder',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stockout_approvals', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AddField(
            model_name='stockoutorder',
            name='status',
            field=models.CharField(choices=[('待审批', '待审批'), ('已批准', '已批准'), ('已拒绝', '已拒绝')], default='待审批', max_length=20, verbose_name='审批状态'),
        ),
    ]
