# Generated by Django 6.0.3 on 2026-05-12 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_stockoutorder_approval_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockinapplication',
            options={'ordering': ['-created_at'], 'verbose_name': '入库单', 'verbose_name_plural': '入库单管理'},
        ),
        migrations.AddField(
            model_name='returnapplication',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='存放位置快照'),
        ),
        migrations.AddField(
            model_name='returnapplication',
            name='specification',
            field=models.CharField(blank=True, max_length=100, verbose_name='规格快照'),
        ),
        migrations.AddField(
            model_name='returnapplication',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, verbose_name='供应商快照'),
        ),
        migrations.AddField(
            model_name='returnapplication',
            name='unit',
            field=models.CharField(default='个', max_length=20, verbose_name='单位快照'),
        ),
        migrations.AddField(
            model_name='stockinitem',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='存放位置快照'),
        ),
        migrations.AddField(
            model_name='stockinitem',
            name='specification',
            field=models.CharField(blank=True, max_length=100, verbose_name='规格快照'),
        ),
        migrations.AddField(
            model_name='stockinitem',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, verbose_name='供应商快照'),
        ),
        migrations.AddField(
            model_name='stockinitem',
            name='unit',
            field=models.CharField(default='个', max_length=20, verbose_name='单位快照'),
        ),
        migrations.AddField(
            model_name='stockoutitem',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='存放位置快照'),
        ),
        migrations.AddField(
            model_name='stockoutitem',
            name='specification',
            field=models.CharField(blank=True, max_length=100, verbose_name='规格快照'),
        ),
        migrations.AddField(
            model_name='stockoutitem',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, verbose_name='供应商快照'),
        ),
        migrations.AddField(
            model_name='stockoutitem',
            name='unit',
            field=models.CharField(default='个', max_length=20, verbose_name='单位快照'),
        ),
        migrations.AlterField(
            model_name='stockinitem',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockinapplication', verbose_name='入库单'),
        ),
    ]
