# Generated by Django 6.0.3 on 2026-05-13 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_stockinapplication_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockoutorder',
            name='dept_approval_comment',
            field=models.TextField(blank=True, verbose_name='部门长审批意见'),
        ),
        migrations.AddField(
            model_name='stockoutorder',
            name='dept_approval_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='部门长审批时间'),
        ),
        migrations.AddField(
            model_name='stockoutorder',
            name='dept_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stockout_dept_approvals', to=settings.AUTH_USER_MODEL, verbose_name='部门长审批人'),
        ),
        migrations.AlterField(
            model_name='stockoutorder',
            name='approval_comment',
            field=models.TextField(blank=True, verbose_name='仓管审批意见'),
        ),
        migrations.AlterField(
            model_name='stockoutorder',
            name='approval_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='仓管审批时间'),
        ),
        migrations.AlterField(
            model_name='stockoutorder',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stockout_approvals', to=settings.AUTH_USER_MODEL, verbose_name='仓管审批人'),
        ),
        migrations.AlterField(
            model_name='stockoutorder',
            name='status',
            field=models.CharField(choices=[('待审批', '待审批'), ('待仓管审批', '待仓管审批'), ('已批准', '已批准'), ('已拒绝', '已拒绝')], default='待审批', max_length=20, verbose_name='审批状态'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('applied_role', models.CharField(choices=[('admin', '管理员'), ('warehouse', '仓管员'), ('dept_head', '部门长'), ('staff', '普通用户')], default='staff', max_length=20, verbose_name='申请角色')),
                ('is_pending', models.BooleanField(default=False, help_text='注册后待管理员审核', verbose_name='待审核')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.department', verbose_name='所属部门')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息管理',
            },
        ),
    ]
